DROP TABLE PROVEEDOR CASCADE CONSTRAINTS;
DROP TABLE DESCUENTO CASCADE CONSTRAINTS;
DROP TABLE EMPLEADO CASCADE CONSTRAINTS;
DROP TABLE SUCURSAL  CASCADE CONSTRAINTS;
DROP TABLE TIPOPRODUCTO CASCADE CONSTRAINTS;
DROP TABLE LOTE CASCADE CONSTRAINTS;
DROP TABLE PRODUCTO  CASCADE CONSTRAINTS;
DROP TABLE DEPOSITOBASURA CASCADE CONSTRAINTS;
DROP TABLE CLIENTE  CASCADE CONSTRAINTS;
DROP TABLE COMPRA CASCADE CONSTRAINTS;
DROP TABLE BODEGA  CASCADE CONSTRAINTS;
DROP TABLE SE_ALMACENA CASCADE CONSTRAINTS;

 
CREATE TABLE PROVEEDOR
(
NITPROVEEDOR NUMBER NOT NULL,
NOMBREPROVEDOR VARCHAR2(50) NOT NULL,
TELEFONOPROVEDOR NUMBER NOT NULL,
CORREOPROVEDOR VARCHAR2(50) NOT NULL,
CONSTRAINT PK_PROVEEDOR PRIMARY KEY (NITPROVEEDOR)
);

CREATE TABLE TIPOPRODUCTO
(
IDTIPOPRODUCTO NUMBER NOT NULL,
NOMBRETIPOPRODUCTO VARCHAR2(50) NOT NULL,
CONSTRAINT PK_TPRO PRIMARY KEY (IDTIPOPRODUCTO)
);

CREATE TABLE LOTE 
(

IDLOTE VARCHAR2(50) NOT NULL,
PRECIOLOTE NUMBER NOT NULL,
CANTIDAD NUMBER NOT NULL,
IDTIPOPRODUCTO NUMBER NOT NULL,
NITPROVEEDOR NUMBER NOT NULL,
CONSTRAINT PK_LOTE PRIMARY KEY (IDLOTE),
CONSTRAINT FK_TPROLOTE FOREIGN KEY (IDTIPOPRODUCTO) REFERENCES TIPOPRODUCTO(IDTIPOPRODUCTO),
CONSTRAINT FK_PROVLOTE FOREIGN KEY (NITPROVEEDOR) REFERENCES PROVEEDOR(NITPROVEEDOR)
);

CREATE TABLE DESCUENTO 
(
CODIGODESCUENTO NUMBER NOT NULL,
PORCENTAJE INTEGER NOT NULL,
CONSTRAINT PK_DESCUENTO PRIMARY KEY (CODIGODESCUENTO)
);

CREATE TABLE EMPLEADO
(
IDEMPLEADO NUMBER NOT NULL,
NOMBREEMPLEADO VARCHAR2(50) NOT NULL,
PRIMERAPELLIDO VARCHAR2(50) NOT NULL,
SEGUNDOAPELLIDO VARCHAR2(50),
TELEFONOEMPLEADO NUMBER NOT NULL,
CORREOEMPLEADO VARCHAR2(50) NOT NULL,
SUELDOEMPLEADO NUMBER NOT NULL,
TIPOEMPLEADO VARCHAR2(50) NOT NULL,
CONSTRAINT PK_EMPLEADO PRIMARY KEY (IDEMPLEADO),
CONSTRAINT CKC_TIPOEMPLEADO CHECK (TIPOEMPLEADO IN('ADMINISTRATIVO','AYUDANTE','CAJERO'))
);

CREATE TABLE SUCURSAL 
(
CODIGOSUCURSAL NUMBER NOT NULL,
NOMBRESUCURSAL VARCHAR2(50) NOT NULL,
DIRECCIONSUCURSAL VARCHAR2(50) NOT NULL,
TELEFONOSUCURSAL VARCHAR2(50) NOT NULL,
IDEMPLEADO NUMBER NOT NULL,
CONSTRAINT PK_SUCURSAL PRIMARY KEY (CODIGOSUCURSAL),
CONSTRAINT FK_EMPSUCURSAL FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADO(IDEMPLEADO)
);

CREATE TABLE PRODUCTO 
(   
NITPRODUCTO NUMBER NOT NULL,
IDLOTE VARCHAR2(50) NOT NULL,
NOMBREPRODUCTO VARCHAR2(50) NOT NULL,
PESOPRODUCTO NUMBER NOT NULL,
PRECIOPRODUCTO NUMBER NOT NULL,
ESTADOPRODUCTO VARCHAR2(30) NOT NULL,
NITPROVEEDOR NUMBER NOT NULL,
CODIGOSUCURSAL NUMBER NOT NULL,
CONSTRAINT PK_PRODUCTO PRIMARY KEY (NITPRODUCTO),
CONSTRAINT UQ_NITLOTE UNIQUE(NITPRODUCTO,IDLOTE),
CONSTRAINT FK_PROVPRO FOREIGN KEY (NITPROVEEDOR) REFERENCES PROVEEDOR(NITPROVEEDOR),
CONSTRAINT FK_LOTEPRO FOREIGN KEY (IDLOTE)REFERENCES LOTE (IDLOTE),
CONSTRAINT FK_SUCUPRO FOREIGN KEY (CODIGOSUCURSAL) REFERENCES SUCURSAL (CODIGOSUCURSAL),
CONSTRAINT CKC_ESTADOPRODUCTO CHECK (ESTADOPRODUCTO IN('BUENO','MALO'))
);

CREATE TABLE DEPOSITOBASURA
(
CODIGODEPOSITO NUMBER NOT NULL,
TIPOBASURA VARCHAR2(50) NOT NULL,
NITPRODUCTO NUMBER NOT NULL,
CONSTRAINT PK_DEPOSITOBASURA PRIMARY KEY (CODIGODEPOSITO),
CONSTRAINT FK_PRODEPO FOREIGN KEY(NITPRODUCTO) REFERENCES PRODUCTO(NITPRODUCTO),
CONSTRAINT CKC_TIPOBASURA CHECK (TIPOBASURA IN('ORGANICA','INORGANICA'))
);

CREATE TABLE CLIENTE 
(
CODIGOCLIENTE NUMBER NOT NULL,
NOMBRECLIENTE VARCHAR2(50) NOT NULL,
PRIMERAPELLIDO VARCHAR2(50) NOT NULL,
SEGUNDOAPELLIDO VARCHAR2(50),
TELEFONOCLIENTE NUMBER NOT NULL,
CORREOCLIENTE VARCHAR2(50) NOT NULL,
DIRECCION VARCHAR2(50) NOT NULL,
CONSTRAINT PK_CLIENTE PRIMARY KEY (CODIGOCLIENTE)
);


CREATE TABLE COMPRA
(
CODIGOCLIENTE NUMBER NOT NULL,
NITPRODUCTO NUMBER NOT NULL,
FECHA DATE NOT NULL,
TIPOPAGO VARCHAR2(30) NOT NULL,
CODIGODESCUENTO NUMBER NOT NULL,
IDEMPLEADO NUMBER NOT NULL,
CONSTRAINT PK_COMPRA PRIMARY KEY (CODIGOCLIENTE,NITPRODUCTO,FECHA ),
CONSTRAINT FK_CLICOMPRA FOREIGN KEY (CODIGOCLIENTE) REFERENCES CLIENTE(CODIGOCLIENTE),
CONSTRAINT FK_DESCOM FOREIGN KEY (CODIGODESCUENTO) REFERENCES DESCUENTO(CODIGODESCUENTO),
CONSTRAINT FK_EMPcOM FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADO(IDEMPLEADO),
CONSTRAINT FK_PROCOMPRA FOREIGN KEY(NITPRODUCTO) REFERENCES PRODUCTO(NITPRODUCTO),
CONSTRAINT CKC_COMPRA CHECK (TIPOPAGO IN('EFECTIVO','TARJETA'))
);

CREATE TABLE BODEGA 
(
CODIGOBODEGA NUMBER NOT NULL,
NOMBREBODEGA VARCHAR2(50) NOT NULL,
IDEMPLEADO NUMBER NOT NULL,
CONSTRAINT PK_BODEGA PRIMARY KEY (CODIGOBODEGA),
CONSTRAINT FK_EMPBODEGA FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADO(IDEMPLEADO)
);

CREATE TABLE SE_ALMACENA
(
CODIGOBODEGA NUMBER NOT NULL,
NITPRODUCTO NUMBER NOT NULL,
FECHA DATE NOT NULL,
CONSTRAINT PK_SEALMACENA PRIMARY KEY (CODIGOBODEGA,NITPRODUCTO,FECHA),
CONSTRAINT FK_BODEALMAC FOREIGN KEY (CODIGOBODEGA) REFERENCES BODEGA(CODIGOBODEGA),
CONSTRAINT FK_PROALMAC FOREIGN KEY(NITPRODUCTO) REFERENCES PRODUCTO(NITPRODUCTO)
);

COMMIT;